### ISSUE TITLE
Send ArchiveMemberExpand into DetailsCollectionList

### ISSUE THREAD

**Issue by iisa** [internetarchive/dweb-archive#101]
Problem:  IAUX is failing the petabox build with the inclusion of the `dweb-archivecontroller` package inside of `DetailsCollectionList` component.

Solution:  Pass in the needed function to the component so that it is a prop.  This removes dweb dependency in IAUX.

**Comment by mitra42** [comment]
Comment made on https://github.com/internetarchive/iaux/pull/155#event-2350346639
