### ISSUE TITLE
GUN: no longer retrieving

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-archive#106]
GUN seems to be down ... apart from #46 which maps to gun's issue https://github.com/amark/gun/issues/590 its no longer retrieving.

**Comment by mitra42** [comment]
Checked in both node and browser, same error that for example `GUN unable to retrieve: gun:/gun/arc/archive.org/metadata/europeanlibraries`

**Comment by mitra42** [comment]
Seems like problem was a regression issue with something no longer working in .once, probably not counting responses. Mark will look into this, for now add a {wait: 2000} to options to .once

**Comment by mitra42** [comment]
Seems like problem was a regression issue with something no longer working in .once, probably not counting responses. Mark will look into this, for now add a {wait: 2000} to options to .once

**Comment by mitra42** [comment]
The error is ...
```
store.js:12 Uncaught (in promise) TypeError: Radisk is not a function
    at Object.eval [as next] (store.js:12)
    at Object.eval [as next] (multicast.js:4)
    at Object.eval [as next] (gun.js:1868)
    at Object.eval [as next] (gun.js:1854)
    at Function.onto [as on] (gun.js:197)
    at Function.Gun.create (gun.js:686)
    at new Gun (gun.js:654)
    at Function.setup0 (TransportGUN.js:109)
    at eval (Transports.js:649)
    at Array.map (<anonymous>)
    at Function.setup0 (Transports.js:642)
    at Function.p_connect (Transports.js:719)
    at main (archive.html?item=commute:98)
    at archive.html?item=commute:110
```

**Comment by amark** [comment]
@mitra42 oh, looks like all you need is `require('gun/lib/radisk')` ... it looks like webpack didn't bundle it even though `store` has a require statement. Go ahead and add radisk, hopefully that'll correct it!

**Comment by mitra42** [comment]
Adding `radisk` then gave an error for `radix` which I added as well. 

I'm still seeing:
```
QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'radata' exceeded the quota. Consider using GUN's IndexedDB plugin for RAD for more storage space, temporary example at https://github.com/amark/gun/blob/master/test/tmp/indexedDB.html 
```
Which makes me wonder if rindexed.js isn't getting loaded properly.  Current setup is ... 
```
const Gun = require('gun/gun.js');  
require('gun/lib/path.js');  
require('gun/lib/radix.js'); 
require('gun/lib/radisk.js');
require('gun/lib/store.js');
require('gun/lib/rindexed.js');
```

**Comment by amark** [comment]
@mitra42 so Webpack is not pulling `require` then? At this point, we've manually included all of them for RAD + IndexedDB. Or it only pulls 1 level deep?

Yeah, I mentioned on call (and in docs, https://gun.eco/docs/RAD#install ) that IndexedDB being turned on does not turn off localStorage, and that you need to pass `Gun({localStorage: false` which is safe/fine for NodeJS & Browser.

Were you able to check IndexedDB if the data was there? Devtools for it are kinda confusing, compared to localStorage, just as a warning.

If you are still getting errors/problems, of course please let me know.

**Comment by amark** [comment]
@mitra42 checking in, is this working?

**Comment by mitra42** [comment]
I was working on a different feature yesterday, I expect to get back to testing this today or tomorrow.

**Comment by mitra42** [comment]
That fixed that problem, but now its not fetching, or at least mostly - I see it fetch metadata for AboutBan1935 but probably from cache somewhere, while it then fails on everything else. There are no error messages of relevance in the console, and I cant' figure out how to get an error out of the .once call

The version with the changes (require's and localStorage: false) is up on dweb.archive.org but its disabled by default, going to `http://localhost:4244/archive/archive.html?transport=HTTP&transport=GUN&identifier=prelinger` will reenable it if you want to debug the networking.  (sorry but the URL gets rewritten to something that can't be reloaded - I'll fix that) 

I *do* see some activity on the gateway where the hikacker is, and it looks correct to my limited knowledge, but dont know how to interpret that.  Its possible that what is happening is that because it fires off multiple queries at the same time, that the combination is timing out on all of them, though I'd expect that to then work ok on a reload if the hijacker was caching the response in its Gun storage.

**Comment by amark** [comment]
http://dweb.me/archive/archive.html?transport=HTTP&transport=GUN&identifier=prelinger

@mitra42 I'm seeing GUN activity via the network tab. Should I, or should I not be seeing that?

And if I do something like:

```
DwebTransports.gun().gun.get('arc').get('archive.org').get('metadata').get('europeanlibraries').once(console.log)
```

I get a response with lots of data.

**Comment by mitra42** [comment]
Which makes me think its related to the timeout bug, i.e. that in practice it fires off a bunch of these queries at the same time, the peer/hijacker takes a while to answer and possibly causes the timeouts to fire. (.once doesnt do any error reporting, so I can't check if that's correct)

**Comment by mitra42** [comment]
Note there is correspondance with mark in email relating to this bug

**Comment by mitra42** [comment]
Closing this as fixed
