### ISSUE TITLE
Update bootloader logic to be hostname independent

### ISSUE THREAD

**Issue by parkan** [internetarchive/dweb-archive#78]
Right now we bail out [here](https://github.com/internetarchive/dweb-archive/blob/94f9317716618ccafdaa867fff0f0ca860c6a471/bootloader.html#L64) if we aren't on a recognized hostname (e.g. https://gateway.ipfs.io/ipfs/QmavNNT7s9YPEv9MJ2nJK95cwfBmJ8os3KDn3CKC4QD8cH/bootloader.html)

Let's make it work regardless of location 😄

**Comment by parkan** [comment]
The name is published under the default entry for the ipfs user on gateway.dweb.me, so it's easy to update:

```
(as user ipfs)
$ ipfs add -r bootloader_dir/
added QmA... dweb-bootloader/bootloader.html
added QmB... dweb-bootloader/dweb-objects-bundle.js
added QmC... dweb-bootloader/dweb-transports-bundle.js
added QmD... dweb-bootloader
ipfs name publish QmD...
``

**Comment by mitra42** [comment]
What its supposed to do (and the Chrome/Firefox extension does) is
* Look at the hostname 
* If it follows a pattern http[s]://dweb.xxx.yyy 
* Look up the name /arc/xxx.yyy in our name table 
* If found boot it
* The extension will pass it on the real dweb.xxx.yyy if it doesn't match, that doesn't make sense for  bootloader.html when that bootloader is coming specifically from dweb.xxx.yyy 

BUT ... I'm not sure how its being loaded in your case above, if its being loaded from some arbitrary site, (via the DNS link) then it probably does make sense to redirect to the site. 

Note - Juan and I met at Dweb and agreed that shipyard, and the extension (and by implication the bootloader) should recognize the same patterns as the ipfs companion, so I'll be a) writing those patterns up from my notes, and then b) extending the bootloader to recognize them. 

That might take a good part of this week as I have to pack up my home by Wednesday as well as knowledge transfer to the rest of the IA team. If you confirm what I'm saying about the DNS link I can have that done early week of the 13th.

**Comment by parkan** [comment]
What dnslink is saying in essence is that instead of resolving dweb.archive.org to 207.241.225.169 (as with the A record) we can also obtain it from an IPFS path specified in the TXT record.

In the firefox nightly + companion + dnslink case the domain part will actually look the same (ipns://dweb.archive.org) so this _should_ just work with current code. However, not everyone will use that, so I wonder if we should allow passing the name key as a ?parameter or similar? i.e. something like https://gateway.ipfs.io/ipfs/QmavNNT7s9YPEv9MJ2nJK95cwfBmJ8os3KDn3CKC4QD8cH/bootloader.html?name=archive.org

**Comment by mitra42** [comment]
Its already got a parameter that i was using for testing, I believe its "url" i.e. if it sees a url=https://dweb.archive.org then it will act as if that had been the URL it was called from.

**Comment by parkan** [comment]
perfect!

**Comment by mitra42** [comment]
Closing this, as the way bootloader works is fine. (there are issues with IPFS not loading properly when loaded from DNSLINK but that's a different issue).
